import React from "react";

import type { Metadata } from "next";

import Navbar from "@/components/layouts/Navbar";

export const metadata: Metadata = {
  title: "Tef Analytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
